### PR TITLE
Use the official lockbox icon throughout

### LINKED ISSUE #151: The Lockbox extension doesn't have any specific icon in "about:addons" page
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.2 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page and click the "Extension" section.
3. Observe the Lockbox extension.

[Expected results]:
- A specific icon is displayed for the extension.

[Actual results]:
- No icon is displayed.

[Notes]:
- Attached a screenshot with the issue:

about addons

locbox icon 2

### LINKED ISSUE #167: The Lockbox tab icon is barely visible when the tab is not focused
[Notes]:
- If the Dark Theme is set, the Lockbox icon is not visible at all.

[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.3 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Lockbox" toolbar icon.
3. Click the "Open Lockbox" button from the displayed doorhanger.
4. Open a new tab.
5. Observe the Lockbox icon from the Lockbox tab.

[Expected results]:
- The icon is visible.

[Actual results]:
- The icon is barely visible.

[Additional Notes]:
- Attached a screenshot with the issue with default theme set:
picturemessage_q1ilfse2 bas

- Attached a screenshot with the issue with dark theme:
picturemessage_0utollig 2sn

### PR DESCRIPTION
**Pull request by 6a68**
* toolbar button icon
* addon icon for about:addons page
* page favicon

Fixes #151, fixes #167.

## Screenshots or Videos

about:addons extensions list view:

Screen Shot 2019-04-29 at 4 27 26 PM

about:addons extension detail view:

Screen Shot 2019-04-29 at 4 27 30 PM

lockbox icon as favicon in backgrounded tab:

Screen Shot 2019-04-29 at 4 27 36 PM

lockbox icon in toolbar, wow so color:
Screen Shot 2019-04-29 at 4 27 40 PM

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding integration tests
- [ ] request the "UX" team perform a design review (if/when applicable)
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-addon/developer/test-plan-accessibility/) of any added UI
- [ ] make sure any new UI has telemetry events wired up and documented in docs/metrics.md, and verify that the events are recording properly (visit `about:telemetry#events-tab`, then choose 'dynamic' from the dropdown menu at top right, to view events fired by the addon

### CODE REVIEW

**Comment by linuxwolf** [comment]
@mozilla-lockbox/product @mozilla-lockbox/ux please note this PR changes the toolbar icon to use the app icon.

I vaguely recall there being concerns using a colored icon in the toolbar, but don't recall specifics about those concerns.  Is this acceptable, or should the previous "monochrome" icon still be used for the toolbar?

**Comment by 6a68** [comment]
Screen Shot 2019-04-29 at 4 42 17 PM

**Comment by 6a68** [comment]
rebased. happy to revert the toolbar button icon if needed :beers:

**Comment by sandysage** [comment]
I have to admit @changecourse is better suited to respond to changing the toolbar icon to use the app icon. But, in the time he's not available, I don't see why we can't use the icon for now. We can always open another issue if we have a suitable replacement in the future. I'm approving.

**Pull request merged**
